//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuCapNhatCongThuc
    {
        public int LichSuId { get; set; }
        public int MonId { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public string NoiDungCapNhat { get; set; }
    
        public virtual Mon Mon { get; set; }
    }
}
